site :opscode

metadata

cookbook 'postgresql'

# Temporary until 1.1.3 is released (see COOK-2806), or I switch to Unicorn
cookbook 'application_ruby', git: 'https://github.com/opscode-cookbooks/application_ruby.git'
